- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: run the shell command
      shell: echo "HelloWorld"
    - name: copy one file to another
      copy:
        src: /home/techmadmin/Desktop/test.txt 
        dest: /tmp/test.txt
        owner: awx
        group: awz
        mode: 0644
      

